// Two-stage bundle, same shape as graphify.
//
// Stage 1 compiles the browser page (page/main.js) into a single minified IIFE
// and writes it into src/generated/pageBundle.ts as a JSON-escaped string
// constant — the page source may freely use backticks / `${`.
//
// Stage 2 is the standard plugin bundle: one CommonJS es2020 file that the
// Extism js-pdk compiler (`extism-js`) turns into the wasm plugin.
const esbuild = require("esbuild");
const fs = require("fs");

async function main() {
  const page = await esbuild.build({
    entryPoints: ["page/main.js"],
    bundle: true,
    minify: true,
    format: "iife",
    target: ["es2020"],
    write: false,
    logLevel: "info",
  });
  const js = page.outputFiles[0].text;
  fs.mkdirSync("src/generated", { recursive: true });
  fs.writeFileSync(
    "src/generated/pageBundle.ts",
    "// GENERATED by esbuild.js (stage 1) — do not edit, not committed.\n" +
      "export const PAGE_JS: string = " +
      JSON.stringify(js) +
      ";\n",
  );

  await esbuild.build({
    entryPoints: ["src/index.ts"],
    outfile: "dist/index.js",
    bundle: true,
    sourcemap: false,
    minify: false,
    format: "cjs",
    target: ["es2020"],
    logLevel: "info",
  });
}

main().catch(() => process.exit(1));
